// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeXAh4ZpZMp4uj2Mfb5FSracPFVtW-lvs',
    appId: '1:61555823001:web:89493fcfc68c868333c308',
    messagingSenderId: '61555823001',
    projectId: 'logmytravel-app',
    authDomain: 'logmytravel-app.firebaseapp.com',
    storageBucket: 'logmytravel-app.firebasestorage.app',
    measurementId: 'G-WSJV7DC7YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztSiYnJB91XLyRa42L7FSCjokWJDjBi8',
    appId: '1:61555823001:android:aa6c1b30992b700f33c308',
    messagingSenderId: '61555823001',
    projectId: 'logmytravel-app',
    storageBucket: 'logmytravel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcn45hWU-zlelr9p6J9oOKGHksoP_3JmY',
    appId: '1:61555823001:ios:5c41c7dc17ef545133c308',
    messagingSenderId: '61555823001',
    projectId: 'logmytravel-app',
    storageBucket: 'logmytravel-app.firebasestorage.app',
    iosBundleId: 'com.example.logMyTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcn45hWU-zlelr9p6J9oOKGHksoP_3JmY',
    appId: '1:61555823001:ios:5c41c7dc17ef545133c308',
    messagingSenderId: '61555823001',
    projectId: 'logmytravel-app',
    storageBucket: 'logmytravel-app.firebasestorage.app',
    iosBundleId: 'com.example.logMyTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeXAh4ZpZMp4uj2Mfb5FSracPFVtW-lvs',
    appId: '1:61555823001:web:b41a1ef37430662d33c308',
    messagingSenderId: '61555823001',
    projectId: 'logmytravel-app',
    authDomain: 'logmytravel-app.firebaseapp.com',
    storageBucket: 'logmytravel-app.firebasestorage.app',
    measurementId: 'G-F80GDR8RF6',
  );
}
